schema_version = "1.0.0"

# KHONG BAO GIO doi `id` sau lan release dau tien.
# Doi id = Blender coi day la add-on khac -> user mat settings va bi cai trung.
id = "ezg_object_spread"
version = "1.2.0"
name = "Object Spread"
tagline = "Xếp pivot object đang chọn thành lưới thẳng hàng, đưa về 0,0,0"
maintainer = "EasyGoing Visual <visual@easygoing.vn>"
type = "add-on"

website = "https://github.com/HuyNg29/3D-EZG-Blender-Addon-Hub"

tags = ["Object", "3D View"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2026 EZG",
]
