schema_version = "1.0.0"

# KHONG BAO GIO doi `id` sau lan release dau tien.
id = "ezg_mixamo_marker_rigger"
version = "0.21.0"
name = "Manual Marker Mixamo Rigger"
tagline = "Dat marker tren T-Pose de sinh armature Mixamo va bind weight"
maintainer = "EasyGoing Visual <visual@easygoing.vn>"
type = "add-on"

website = "https://github.com/HuyNg29/3D-EZG-Blender-Addon-Hub"

tags = ["Rigging", "Animation"]

# Extensions chi ton tai tu Blender 4.2 tro len.
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2026 EasyGoing Visual",
]
